### ISSUE TITLE
I was just reading your code when...

### ISSUE THREAD

**Issue by pateketrueke** [sveltejs/svelte-extras#8]
Hi, probably I'm just dumb, but why the loop here?

https://github.com/sveltejs/svelte-extras/blob/06ef4237360d47e60dd1298a0359a88fb2d59bf7/src/spring.ts#L218-L220

**Comment by Rich-Harris** [comment]
Whoops! Well spotted. It's supposed to ensure that any calls to `spring` are cancelled by subsequent calls to `set` on the same key...

```js
component.spring('x', 100, {...});

// some time later, the spring simulation is still running
component.set({ x: 200 }); // we need to cancel the simulation immediately
```

...but clearly isn't doing that. Fix inbound, thanks.
